################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
win32/common \
tools \
tests/icles \
tests/icles/playback \
tests/examples/snapshot \
tests/examples/seek \
tests/examples/playrec \
tests/examples/playback \
tests/examples/overlay \
tests/examples/gio \
tests/examples/fft \
tests/examples/encoding \
tests/examples/dynamic \
tests/examples/audio \
tests/examples/app \
tests/check/pipelines \
tests/check/libs \
tests/check/gst \
tests/check/generic \
tests/check/elements \
sys/xvimage \
sys/xvimage/.libs \
sys/ximage \
sys/ximage/.libs \
gst-libs/gst/video \
gst-libs/gst/video/.libs \
gst-libs/gst/tag \
gst-libs/gst/tag/.libs \
gst-libs/gst/sdp \
gst-libs/gst/sdp/.libs \
gst-libs/gst/rtsp \
gst-libs/gst/rtsp/.libs \
gst-libs/gst/rtp \
gst-libs/gst/rtp/.libs \
gst-libs/gst/riff \
gst-libs/gst/riff/.libs \
gst-libs/gst/pbutils \
gst-libs/gst/pbutils/.libs \
gst-libs/gst/fft \
gst-libs/gst/fft/.libs \
gst-libs/gst/audio \
gst-libs/gst/audio/.libs \
gst-libs/gst/app \
gst-libs/gst/app/.libs \
gst-libs/gst/allocators \
gst-libs/gst/allocators/.libs \
gst/volume \
gst/volume/.libs \
gst/videotestsrc \
gst/videotestsrc/.libs \
gst/videoscale \
gst/videoscale/.libs \
gst/videorate \
gst/videorate/.libs \
gst/videoconvert \
gst/videoconvert/.libs \
gst/typefind \
gst/typefind/.libs \
gst/tcp \
gst/tcp/.libs \
gst/subparse \
gst/subparse/.libs \
gst/playback \
gst/playback/.libs \
gst/gio \
gst/gio/.libs \
gst/encoding \
gst/encoding/.libs \
gst/audiotestsrc \
gst/audiotestsrc/.libs \
gst/audioresample \
gst/audioresample/.libs \
gst/audiorate \
gst/audiorate/.libs \
gst/audioconvert \
gst/audioconvert/.libs \
gst/app \
gst/app/.libs \
gst/adder \
gst/adder/.libs \
ext/vorbis \
ext/vorbis/.libs \
ext/theora \
ext/theora/.libs \
ext/pango \
ext/pango/.libs \
ext/ogg \
ext/ogg/.libs \
ext/libvisual \
ext/libvisual/.libs \
ext/cdparanoia \
ext/cdparanoia/.libs \
ext/alsa \
ext/alsa/.libs \
docs/libs/.libs \

